# Site settings
title: Jelmer Snoeck
email: jelmer@siphoc.com
description: > # this means to ignore newlines until "baseurl:"
  Projects and thoughts from Jelmer Snoeck, Platform Engineer.
baseurl:
url: https://jelmersnoeck.com
twitter_username: jelmersnoeck
github_username:  jelmersnoeck

gems:
  - jekyll-paginate
  - jekyll-feed

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  portfolio:
    output: true
    permalink: /projects/:path/
